### ISSUE TITLE
Why do we need a timer to scan the peripherals on frequent intervals ? 

### ISSUE THREAD

**Issue by SKS54** [gundrabur/BLEScanner#1]
Why do we need a timer to scan the peripherals on frequent intervals ? Ideally, starting it once should continue to detect the beacons, correct ?

**Comment by gundrabur** [comment]
This is correct. We don't need a timer for that. I implemented it anyway to get more control over the scanning procedure, I had the impression it may save battery ...

**Comment by SKS54** [comment]
Ooh got it, so did it help ?

**Comment by gundrabur** [comment]
I didn't take exact measurements, but based on my experience I think it was worth it.
